"""Update Posts Table w with bmi

Revision ID: 60f6f82e036b
Revises: 63fa43009b12
Create Date: 2018-07-29 09:59:56.016996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f6f82e036b'
down_revision = '63fa43009b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('bmireport', sa.String(length=64), nullable=True))
    op.add_column('post', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('post', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('post', sa.Column('weight', sa.Float(), nullable=True))
    op.create_index(op.f('ix_post_name'), 'post', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_name'), table_name='post')
    op.drop_column('post', 'weight')
    op.drop_column('post', 'name')
    op.drop_column('post', 'height')
    op.drop_column('post', 'bmireport')
    op.drop_column('post', 'bmi')
    # ### end Alembic commands ###
