"""PatientImage  Model

Revision ID: 63fa43009b12
Revises: f5b0315165e0
Create Date: 2018-07-27 00:57:14.544704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fa43009b12'
down_revision = 'f5b0315165e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_coordinates', sa.String(length=50), nullable=True),
    sa.Column('imageurl', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_images')
    # ### end Alembic commands ###
