"""Patient Model

Revision ID: 64fb26819d4f
Revises: 1f3baa1921c7
Create Date: 2018-07-27 00:50:36.593722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fb26819d4f'
down_revision = '1f3baa1921c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('patient_description', sa.String(length=300), nullable=True),
    sa.Column('patient_lat', sa.Float(), nullable=False),
    sa.Column('patient_lng', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_timestamp'), 'patient', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_timestamp'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
