"""Walks Model

Revision ID: 79556a0faaef
Revises: 64fb26819d4f
Create Date: 2018-07-27 00:54:02.924766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79556a0faaef'
down_revision = '64fb26819d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walks',
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('log_datetime', sa.Date(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['origin'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('walk_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walks')
    # ### end Alembic commands ###
