"""WalkPatientLink Model

Revision ID: f5b0315165e0
Revises: 79556a0faaef
Create Date: 2018-07-27 00:55:49.719217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b0315165e0'
down_revision = '79556a0faaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walk_patient_link',
    sa.Column('walk_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['walks.walk_id'], ),
    sa.PrimaryKeyConstraint('walk_id', 'patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walk_patient_link')
    # ### end Alembic commands ###
